### ISSUE TITLE
Record bpm on button press instead of button release

### ISSUE THREAD

**Issue by Portagoras** [Kr0oked/Metronome#17]
I guess the title says it all. Currently it counts the time when a button is release when tapping a bpm into the app. This is unintuitive I think, cause it differes when you release your finder from your screen.

**Comment by Kr0oked** [comment]
Thanks for opening the issue. That is something I also wanted to implement for quiet some time. I implemented it in fb21865bcacced83b36a5a1996c246654cf1b069 and it will be shipped in the next version. Regards
