### ISSUE TITLE
Feature Request: Time Elapsed

### ISSUE THREAD

**Issue by alensiljak** [Kr0oked/Metronome#2]
Thanks a lot for the app! Looks promising. I'd like to throw some ideas out, if you'd be interested to adding features to the app.

This one is for a timer to run while the metronome is ticking. I like to see the time elapsed while doing an exercise.

This can later evolve into stopping an exercise once the foreseen time is reached.

**Comment by Kr0oked** [comment]
Hi @MisterY, 
thanks for the suggestions. I am always open for ideas that correspond to the apps objectives.
I like the idea of having a timer that tracks the ticking time. Maybe I will include it at some point.
But setting up a time after that the metronome automatically stops makes the apps handling probably more complicated which I want to avoid right now.

**Comment by driebe** [comment]
To add to this: I believe if you'd use a play/pause/stop button logic with just one time counter running at any time, it would be still be easy to use. If I know I do 1,2,5minute workouts, there's (from my perspective) no need to set up timers in the app since I can just watch the timer...

**Comment by alensiljak** [comment]
Doesn't matter. There are much better metronome apps out there, that do timed sets of exercises with transitions, etc. Horses for courses.
