### ISSUE TITLE
Missing Chinese and Spanish language

### ISSUE THREAD

**Issue by siyunesweek** [Kr0oked/Metronome#24]
I am using this app, and it is what i was looking for a simple metronome, but I noticed that it hasn't been translated into either Chinese or Spanish. I am interested in contributing to that part. Can I? How would I need to do it?

**Comment by Kr0oked** [comment]
Hi, thanks for offering your help with translations.

There are two general things that need to be translated. The text used in the app and the store texts.

You have to translate this file here https://github.com/Kr0oked/Metronome/blob/master/app/src/main/res/values/strings.xml and put it in a new directory with the locale suffix like this one here for german with the 'de' suffix https://github.com/Kr0oked/Metronome/tree/master/app/src/main/res/values-de .

Then you have to translate the medata texts in title.txt, short_description.txt and full_description.txt from here https://github.com/Kr0oked/Metronome/tree/master/fastlane/metadata/android/en-US . The translated files can be placed in another folder with the locale suffix like here for german https://github.com/Kr0oked/Metronome/tree/master/fastlane/metadata/android/de . You can ignore all the other files in that directories.

If you are not familiar with Git you can also just attach the four translated files here in the chat and I will add them myself.

Thanks in advance!

**Comment by siyunesweek** [comment]
I just made a fork and I will try to make all the changes there and then make a pull request. But if you prefer, i can attach the files here. Whatever you like.

**Comment by Kr0oked** [comment]
A pull request is perfectly fine

**Comment by Kr0oked** [comment]
Implemented in b04646d412054cadab6fac1c155505bebf93b5de
