### ISSUE TITLE
Improve metronome precision

### ISSUE THREAD

**Issue by Kr0oked** [Kr0oked/Metronome#3]
Currently the metronome is out of sync. This issue is clearly audible. Especially with a high tempo and lot of subdivisions.
This is because of the standard [Timer](https://developer.android.com/reference/java/util/Timer) class. The scheduled task is often 10ms or more behind the actual planned execution.

When scheduling ticks with a typical Thread-sleep mechanism the precision will probably never be good enough to sort out this issue.
Instead we should investigate an approach that writes the audio data in before to an [AudioTrack](https://developer.android.com/reference/android/media/AudioTrack) so it gets played exactly in time.

**Comment by strk** [comment]
Yes please, I noticed this too and thus uninstalled the app. An out of time metronome makes no sense. But thanks for sharing your work !
