### ISSUE TITLE
Customize the metronome volume

### ISSUE THREAD

**Issue by tch123** [Kr0oked/Metronome#41]
When I use a metronome, I usually also play music from another app, and it's great that both apps can play simultaneously. When I want to adjust the volume of the music or the metronome, using the volume buttons affects both apps' volumes together. Can the metronome have its own volume control that isn't influenced by the system volume buttons? Or is there a way to adjust the volume of different apps individually?

**Comment by Kr0oked** [comment]
It is not possible to control the volume per application.
For convinience I will not implement a parallel volume control in the app.
