### ISSUE TITLE
Accessibility issues in GUIs 

### ISSUE THREAD

**Issue by Kazaf123** [Kr0oked/Metronome#7]
**Description**
This is a bug report about components that have accessibility issues within the GUI of such an App.
Also, as the following Figure, this report focuses on the content GUI page in the App.
<img width="360" alt="MuMu20221128084549" src="https://user-images.githubusercontent.com/44084361/204169613-960e47c6-11bf-4f0b-a4b6-8993b179f59b.png">
**Content**
After I applied my proposed tool to detect the content page, I discovered the following components which have accessibility issues, and I sincerely struggled you could repair these issues so that visually impaired users would use this App more conveniently.
As for these texts in GUI, they are too small for low-vision users to see, could you make them larger?

**Comment by Kr0oked** [comment]
Thanks for reporting. I will see what I can do for the accessibility issues. I am also already planning to improve the UI  to look better on larger screens. At the moment the UI only looks good on medium size displays.

**Comment by Kr0oked** [comment]
I will keep the current text size because it follows the official guidelines. Please keep in mind that visually impaired users can increase the text size as described in [Change text & display settings](https://support.google.com/accessibility/android/answer/11183305?hl=en)
