### ISSUE TITLE
No visual feedback

### ISSUE THREAD

**Issue by fanglingsu** [Kr0oked/Metronome#8]
I can't see any color changes on the big beat dots. I tryed to change from dark to light mode, but all dots look the same if the metronome ticks. As I understand they should give some visual feedback about the beats.
Any suggest what I could change to have this visual feedback?

**Comment by Kr0oked** [comment]
Yes the color of the dot representing the current tick should blink in a different color. Could you give some details about your device? Maybe other users experience the same issue.

**Comment by fanglingsu** [comment]
My device is a samsung a22 with android 13. Do you need other information too?

**Comment by Kr0oked** [comment]
Unfortunately I cannot reproduce the issue and I have no idea what could cause this issue. So I will keep this issue open and hope to find a solution later on.

**Comment by blamarche** [comment]
I'm also getting this issue on a Galaxy A03s on Android 12.

**Comment by fanglingsu** [comment]
I've updated the App via F-Droid to Version 1.4.1 and I can now see the visual dots. Was there changed anything?

**Comment by Kr0oked** [comment]
> I've updated the App via F-Droid to Version 1.4.1 and I can now see the visual dots. Was there changed anything?

There was no change regarding the dots in  version 1.4.1. But  I made a change in the previous version 1.4 where I made use of another animation mechanism. Could you install the old versions 1.3 and 1.4 and tell me if in which of them you get the faulty behaviour? You can still install them from F-Droid.

**Comment by fanglingsu** [comment]
@Kr0oked I've tested all versions. 1.3 has  the issue. 1.4 as well as 1.4.1 run without any issue for me.

**Comment by Kr0oked** [comment]
> @Kr0oked I've tested all versions. 1.3 has the issue. 1.4 as well as 1.4.1 run without any issue for me. For me the issue is solved.

Thanks for testing the versions. In that case it must have been the commit in 1.4 https://github.com/Kr0oked/Metronome/commit/4e44314a18aeea261c7fffa56c6efdf825ad831a that solves the issue.
